In [1]:
import numpy as np  # linear algebra
import pandas as pd  # data processing, CSV file I/O (e.g. pd.read_csv)

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import train_test_split, cross_val_score

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.metrics import roc_curve, auc, roc_auc_score
import os

In [2]:
train_df = pd.read_csv('jigsaw-unintended-bias-in-toxicity-classification/train.csv')
test_df = pd.read_csv('jigsaw-unintended-bias-in-toxicity-classification/test.csv')
sub = pd.read_csv('jigsaw-unintended-bias-in-toxicity-classification/sample_submission.csv')

In [36]:
df = train_df.copy()

In [37]:
df.head()

,id,target,comment_text,severe_toxicity,obscene,identity_attack,insult,threat,asian,atheist,...,article_id,rating,funny,wow,sad,likes,disagree,sexual_explicit,identity_annotator_count,toxicity_annotator_count
0,59848,0.000000,"This is so cool. It's like, 'would you want yo...",0.000000,0.0,0.000000,0.00000,0.0,NaN,NaN,...,2006,rejected,0,0,0,0,0,0.0,0,4
1,59849,0.000000,Thank you!! This would make my life a lot less...,0.000000,0.0,0.000000,0.00000,0.0,NaN,NaN,...,2006,rejected,0,0,0,0,0,0.0,0,4
2,59852,0.000000,This is such an urgent design problem; kudos t...,0.000000,0.0,0.000000,0.00000,0.0,NaN,NaN,...,2006,rejected,0,0,0,0,0,0.0,0,4
3,59855,0.000000,Is this something I'll be able to install on m...,0.000000,0.0,0.000000,0.00000,0.0,NaN,NaN,...,2006,rejected,0,0,0,0,0,0.0,0,4
4,59856,0.893617,haha you guys are a bunch of losers.,0.021277,0.0,0.021277,0.87234,0.0,0.0,0.0,...,2006,rejected,0,0,0,1,0,0.0,4,47

In [38]:
df.dropna(axis=0, inplace=True)
df.head()

,id,target,comment_text,severe_toxicity,obscene,identity_attack,insult,threat,asian,atheist,...,article_id,rating,funny,wow,sad,likes,disagree,sexual_explicit,identity_annotator_count,toxicity_annotator_count
11,239579,0.4400,This is a great story. Man. I wonder if the pe...,0.00,0.293333,0.0000,0.3200,0.0000,0.0,0.0,...,26650,approved,0,0,0,1,0,0.04,10,75
31,239607,0.9125,Yet call out all Muslims for the acts of a few...,0.05,0.237500,0.6125,0.8875,0.1125,0.0,0.0,...,26670,approved,0,0,0,1,0,0.00,4,80
51,239644,0.0000,Because the people who drive cars more are the...,0.00,0.000000,0.0000,0.0000,0.0000,0.0,0.0,...,26673,approved,0,0,0,0,0,0.00,4,4
58,239653,0.3000,Mormons have had a complicated relationship wi...,0.00,0.000000,0.3000,0.0000,0.0000,0.0,0.0,...,26670,approved,0,0,0,2,0,0.00,10,10
111,239744,0.0000,I'm doing the same thing! :),0.00,0.000000,0.0000,0.0000,0.0000,0.0,0.0,...,26795,approved,0,0,0,1,0,0.00,4,4

In [39]:
Vectorize = TfidfVectorizer()

X = Vectorize.fit_transform(df["comment_text"])

test_X = Vectorize.transform(test_df["comment_text"])

In [40]:
y = np.where(train_df["target"] >= 0.5, 1, 0)

In [41]:
X.shape, y.shape, test_X.shape

((235085, 114308), (1804874,), (97320, 114308))

In [44]:
X_train, X_test, y_train, y_test = train_test_split(
	X.toarray(), y, test_size=1 / 3, random_state=42, stratify=y, shuffle=True
)

: